### ISSUE TITLE
FetchError: request to https://pastebin.com/api/api_login.php failed, reason: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by isitreallyalive** [cAttte/pastebin.js#1]
![image](https://user-images.githubusercontent.com/19301186/120317202-4026b300-c2d6-11eb-91f5-bb1170514224.png)

I am developing a Discord bot and one of the features requires me to upload a paste to Pastebin, so I decided to try using your library. Even just logging in, I am getting the error above. Why is this happening?

**Comment by isitreallyalive** [comment]
Investigating, tried making some curl requests with similar errors. Tried other libraries with no success, friends are having problems with curl too. Contacting pastebin support rn

**Comment by cAttte** [comment]
hey! that error seems to be caused by a faulty SSL certificate on Pastebin's side. i don't have a lot of time to test right now, but i'm assuming it's been solved. feel free to update! (maybe we could fall back to using HTTP when catching this error, with a warning?)

also, please report if you find any other issues, i haven't really developed this library in quite a while!

**Comment by isitreallyalive** [comment]
It still doesn't seem to have been fixed by itself - waiting on a response from Pastebin, will keep you up to date! That fallback might be a good idea to implement either way

**Comment by cAttte** [comment]
thanks!

testing it with the following code:

```js
const { PastebinClient } = require("@catte_/pastebin.js")

new PastebinClient("...", "...", "...")
    .login()
    .then(client => console.log(client.credentials.userKey))
```

is not throwing any errors and is generating a seemingly valid user key for me, so it may not actually be a Pastebin issue (or at least, not a global one). though it's weird that it's not working for your friends either (unless they live somewhere near you?).

anyways, i found a workaround [here](https://stackoverflow.com/a/50959031), but i wouldn't recommend it as a permanent solution (or for production):

```js
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"
const client = new PastebinClient(...)
```

that should avoid the error. i'm not sure if using an HTTP URL would work at all, but you can also try that if you'd like (by changing it in `node_modules/@catte_/pastebin.js/dist/struct/PastebinClient.js`). if this doesn't get fixed soon, we could add a `rejectUnauthorized` or `useHTTP` option (or something like that) to the client.

**Comment by isitreallyalive** [comment]
That TLS REJECT did in fact work, however setting it to http in the package's code seemed to not work for whatever reason. I'm still waiting on a reply from pastebin, so I don't know what's happening really. It's pretty weird, I guess I'll just have to use TLS_REJECT_UNAUTHORIZED for the mean time - thank you for the work around and the help though, it's much appreciated ^w^
